# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V4oIapqPT97CFBpAv9I9BC4uhElNvlTL
"""

n = 7;
print(n*n)